### ISSUE TITLE
Plugins guardians - capability checking needs to be added.

### ISSUE THREAD

**Issue by mchurchward** [vadimonus/moodle-local_purgequestioncategory#1]
I believe you should be testing the capability 'local/purgequestioncategory:purgecategory' in all of your main level scripts, such as "category.php". While you check for them in the library functions that add the links to the navigation menus, the scripts could be called directly from the web URL. Therefore I think you need to check that capability there as well. 
As a test, I added the capability "moodle/question:managecategory" to a student at a course level, and accessed "/local/purgequestioncategory/category.php?cmid=xx" direct. Instead of getting a permissions error, the function through a coding error. Testing for the "purgecategory" capability at the top of this script would resolve that.
Since this is a top-level callable script, you should also check for login.
These comments also apply to "confirm.php".

**Comment by vadimonus** [comment]
Hello, Mike Churchward.
You should know, that category.php in this plugin and in my local_quickrenamequestioncategories plugin replicates core /question/category.php page. So, you should firstly examine that script for the same problems, post tracker issue and put number here. After that issue is closed, i will replicate it behaviour here.
Currently i cannot check permission on the start of page loading, at this page can show categories in many contextes, and it's not
As for confirm.php, i will add permission check before processing harmful action.
As for defined('MOODLE_INTERNAL') || die() into classes, i replicate behaviour of most of classes file in core. If you think it should be done for all classes, you should create corresponding issue for moodle code checher. I think creating codechecker rule for defined('MOODLE_INTERNAL') || die() on start of any class file would be best practice

**Comment by mchurchward** [comment]
Hi Vadim -
"/question/category.php" won't have the capability problem, because the code below it (in the various libraries) checks for standard core capabilities it know about. The problem with your plugin is it has a new capability that is not checked below, meaning you need to check it at the plugin level first.

I agree that core is inconsistent with its use of "defined('MOODLE_INTERNAL') || die()", but they do tend to add it to new code. They just aren't retroactively doing it with old code. For example, you can see it here "/admin/roles/classes/admins_potential_selector.php".

Thanks!

**Comment by mudrd8mz** [comment]
Mike said:

bq. Testing for the "purgecategory" capability at the top of this script would resolve that.

But it would only lead to another access control exception thrown just earlier, right? As far as I can see, if the user does not have the capability "local/purgequestioncategory:purgecategory":
* They can't see the tool in the navigation
* Attempting to access it directly via URL (such as category.php or confirm.php) correctly leads to access exception thrown by `require_capability()`.

And that is expected behaviour.

**Comment by mchurchward** [comment]
@David -
You said, "Attempting to access it directly via URL (such as category.php or confirm.php) correctly leads to access exception thrown by require_capability()."
That isn't true. Accessing directly by URL will throw an access exception if the user does not have "any" of the capabilities defined within the core question code. It never checks of the user has "local/purgequestioncategory:purgecategory". So if the user has one of the core question capabilities defined within the core question code, they will pass the "require_capability" test, even if they do not have the "local/purgequestioncategory:purgecategory".
When I tested this case, it caused a fatal coding error.
It seems to me that to execute code that requires a specific capability, that capability should be confirmed.

**Comment by mudrd8mz** [comment]
I see. Yeah, I admit I have not tested all possible scenarios so yes I can imagine that in untypical permissions setup (like "can manager questions categories but can't purge them") the behaviour could be improved. I agree that simply adding `reguire_capability()` to all the front end scripts would be best approach here (and I do not agree with "core does not do it" argument, basically for the same reasoning that Mike already mentioned).

So yes, this issue is valid. It is not IMHO a blocker for approval and I believe that Vadim will address it in the next update.

**Comment by vadimonus** [comment]
This issue is alredy closed and posted on github and moodle.org.
Category.php shows list of categories you can purge (even if accessed by url). If you have manage access, and do not have purge capabiliy, you'll see empty list. Previously there was error, it's fixed. 
Confirm.php checks capability.
I have decided to create permission for this plugin because purging thousands of questions in three clicks is too dangerous, and someone may want to grant this ability only to special role.
