### ISSUE TITLE
Usability: "Top" is not a valid category

### ISSUE THREAD

**Issue by mudrd8mz** [vadimonus/moodle-local_purgequestioncategory#5]
When selecting a category to move questions to, I can't select the "Top" category.

![screenshot_2016-05-12_12-30-14](https://cloud.githubusercontent.com/assets/85831/15211735/4ebb0b6c-183d-11e6-9972-2b40ee7bc7fb.png)

**Comment by vadimonus** [comment]
Yes, that's by design. But this have a long story, that i want to tell you, as you have noticed this.
I spent a whole day to setup questioncategory mform element to behave the way i need. It should not show Top, because questions must belong to category. On the other hand it should not show selected category and all of it's children, you can move questions there, as they will be deleted.
But error in this element implementation does not remove selected category and it's children if Top is not shown. 
The problem is in function flatten_category_tree function in /lib/questionlib.php, if you look at it, youll see, it compares only children with $nochildrenof param, and does not check top level items. So if Top is not shown, categories becomes top level items and they are not wiped.
I do not clearly understand how to modify this function and not to break something accidentally, so i have not created patch. As far as currently I am the only user of such options combination, i decided not to post tracker issue (it's hard to describe problem on ttracker and i'm afraid such special issue will never be closed). I decided just to show Top item and then validate, that it's not selected.
Now, when you know everything, it's on your conscience to open such issue.

**Comment by mudrd8mz** [comment]
Ok, thanks. Good to see this was not just missed and you are aware of it.
